version: "3.7"
services:
  backend:
    build: .
    ports:
      - 5000:5000
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_CURSORCLASS: ${MYSQL_CURSORCLASS}

